# Override the default port through environment variable
server:
  port: ${PORT:8080}

# PostgreSQL database configuration
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  # JPA configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true